{% set name = "pgsu" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51dbb8f2272deacc28f546af442a1411eb260b1da53e11d4f93ea90f2b1acf50

build:
  number: 0
  noarch: python
  entry_points:
    - pgsu=pgsu.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - psycopg2 >=2.8.3

test:
  imports:
    - pgsu
  commands:
    - pgsu --help

about:
  home: https://github.com/aiidateam/pgsu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Connect to an existing PostgreSQL cluster as a postgres superuser and execute SQL commands.
  dev_url: https://github.com/aiidateam/pgsu

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
