{% set name = "pgsu" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfad6a8505a7ad3412c5d4e958886a41f46cf6fa828f9f57d08fbbe3c1a629da

build:
  number: 0
  entry_points:
    - pgsu=pgsu.cli:run
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [ py > 38]

requirements:
  host:
    - pip
    - python
  run:
    - click
    - enum34   # [py<35]
    - psycopg2 >=2.8.3
    - python

test:
  imports:
    - pgsu
  commands:
    - pgsu --help

about:
  home: https://github.com/aiidateam/pgsu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Connect to an existing PostgreSQL cluster as a postgres superuser and execute SQL commands.
  dev_url: https://github.com/aiidateam/pgsu

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
